// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7WTPLY2MH8hJ2BcHtSZKbJP8vjpge0o',
    appId: '1:1091650049239:web:f42913ce6c182901e90c92',
    messagingSenderId: '1091650049239',
    projectId: 'myfixpal-1',
    authDomain: 'myfixpal-1.firebaseapp.com',
    storageBucket: 'myfixpal-1.firebasestorage.app',
    measurementId: 'G-TZG0NLCHML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPls18iAu1MrgvSEokv_G0Q7hDywoGwrQ',
    appId: '1:1091650049239:android:ec42a54744357a1ae90c92',
    messagingSenderId: '1091650049239',
    projectId: 'myfixpal-1',
    storageBucket: 'myfixpal-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEVM5p1UuIaiN7dOPsqB8uodyMkvrOXs',
    appId: '1:1091650049239:ios:3b3a2102bf283b58e90c92',
    messagingSenderId: '1091650049239',
    projectId: 'myfixpal-1',
    storageBucket: 'myfixpal-1.firebasestorage.app',
    iosBundleId: 'com.example.myfixpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEVM5p1UuIaiN7dOPsqB8uodyMkvrOXs',
    appId: '1:1091650049239:ios:3b3a2102bf283b58e90c92',
    messagingSenderId: '1091650049239',
    projectId: 'myfixpal-1',
    storageBucket: 'myfixpal-1.firebasestorage.app',
    iosBundleId: 'com.example.myfixpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl7WTPLY2MH8hJ2BcHtSZKbJP8vjpge0o',
    appId: '1:1091650049239:web:a4c59963f98be9fae90c92',
    messagingSenderId: '1091650049239',
    projectId: 'myfixpal-1',
    authDomain: 'myfixpal-1.firebaseapp.com',
    storageBucket: 'myfixpal-1.firebasestorage.app',
    measurementId: 'G-Q5DLXM4RDY',
  );
}
